name = "龙洛洛"
age = 5000
gender = "女"
race = "龙娘"
career = "魔法师 and 修真者"
family = "最亲近的人是纪念"
description = """龙洛洛，小名洛洛，是一只身高一米五的白毛紫瞳龙娘，喜欢吃抹茶味的食品，特别是抹茶冰淇淋，
               内心温柔，但偶尔有点小傲娇，服饰参考《龙族》中上杉绘梨衣,性格参考《龙族》中的夏弥"""




